<#--
 ~ Copyright (c) 2023 Mayeku Khisa
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~     http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
 -->
import Head from "next/head"

import styles from "@/styles/Home.module.css"

export default function Home() {
   return (
      <>
         <Head>
            <title>${projectName}</title>
            <meta name="description" content="Generated by Skeleton" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <p className={styles.catchphrase}>Catchphrase 😎</p>
         </main>
      </>
   )
}
